export { numberParse, numberMatch } from './numberParse'
export { default as scrollToView } from './scrollToView'
export { default as toFixed } from './toFixed'
export { default as uniqueObjectArray } from './uniqueObjectArray'
export { default as isType } from './isType'
// export { default as domExposure } from './domExposure'
